---

- name: load zookeeper-service
  shell: >
    {{ chkconfig_cmd }} {{ chkconfig_opts }} {{ zk_service }} {{ chkconfig_args }}
    
- name: zookeeper-service
  command: service {{ zk_service }} status
  ignore_errors: yes
  register: zookeeper_service_status
  notify:
    - initialize zookeeper-service
    - restart zookeeper-service

# Because sudo doesn't work for my development platform
# so the permissions are screwy
- name: initialize zookeeper-service
  shell: service {{ zk_service }} init; chown -R {{ zk_user }}:{{ zk_group }} {{ zk_tree.vlb }}
  ignore_errors: yes
  when: zookeeper_service_status|failed
  notify:
    - zookeeper-service id file
    - start zookeeper-service

- name: zookeeper-service id file
  template: src=myid.j2 dest={{ zk_tree.vlb }}/myid
    mode=0644 owner={{ zk_user }} group={{ zk_group }} backup=no
  notify: 
    - delete standalone myid file
    - start zookeeper-service

- name: delete standalone myid file
  shell: grep -q '^\s*$' myid && rm myid chdir={{ zk_tree.vlb }} removes={{ zk_tree.vlb }}/myid 
  ignore_errors: yes
  notify: start zookeeper-service
    
- name: start zookeeper-service
  command: service {{ zk_service }} start
  notify: check zookeeper-service status
  
- name: restart zookeeper-service
  command: service {{ zk_service }} restart
  when: zookeeper_service_status|success
  notify: check zookeeper-service status

- name: check zookeeper-service status
  command: service {{ zk_service }} status
